[package]
name = "sqlite-vec"
license = "MIT OR Apache"
homepage = "https://alexgarcia.xyz/sqlite-vec"
repo = "https://github.com/asg017/sqlite-vec"
description = "A vector search SQLite extension."
authors = ["Alex Garcia"]
git_tag_format = "v$VERSION"

[targets]
github_releases = {}
sqlpkg = {}
spm = {}
amalgamation = {include=["sqlite-vec.c", "sqlite-vec.h"]}

pip = { extra_init_py = "bindings/python/extra_init.py" }
datasette = {}
sqlite_utils = {}

npm = {}

gem = { module_name = "SqliteVec" }
